"""empty message

Revision ID: 3852d54bfd2c
Revises: fb2e21a62b1e
Create Date: 2020-08-12 13:36:58.869674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3852d54bfd2c'
down_revision = 'fb2e21a62b1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grades',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=225), nullable=False),
    sa.Column('scale', sa.String(length=225), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.add_column('gunplas', sa.Column('grade_code', sa.String(length=20), nullable=False))
    op.create_foreign_key(None, 'gunplas', 'grades', ['grade_code'], ['code'])
    op.drop_column('gunplas', 'grade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gunplas', sa.Column('grade', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'gunplas', type_='foreignkey')
    op.drop_column('gunplas', 'grade_code')
    op.drop_table('grades')
    # ### end Alembic commands ###
