"""empty message

Revision ID: fb2e21a62b1e
Revises: 
Create Date: 2020-07-26 21:42:25.793438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb2e21a62b1e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=225), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('premiered', sa.String(length=50), nullable=False),
    sa.Column('studio', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('gunplas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=225), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('grade', sa.String(length=20), nullable=False),
    sa.Column('scale', sa.String(length=20), nullable=True),
    sa.Column('price', sa.Float(precision=2), nullable=False),
    sa.Column('release_date', sa.DateTime(), nullable=True),
    sa.Column('brand', sa.String(length=40), nullable=True),
    sa.Column('serie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['serie_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gunplas')
    op.drop_table('users')
    op.drop_table('series')
    # ### end Alembic commands ###
